'\" -*- coding: utf-8 -*-
'\" vim:fenc=utf-8
.if \n(.g .ds T< \\FC
.if \n(.g .ds T> \\F[\n[.fam]]
.de URL
\\$2 \(la\\$1\(ra\\$3
..
.if \n(.g .mso www.tmac
.TH ayatana-webmail-clear 1 "Oct 2023" "Version 23.10.13" "Ayatana Webmail"
.SH NAME
ayatana-webmail-clear \- Webmail Integration into your Desktop
.SH SYNOPSIS
'nh
.fi
.ad l
\fBayatana-webmail-clear\fR \kx
.if (\nx>(\n(.l/2)) .nr x (\n(.l/5)
'in \n(.iu+\nxu
[
\fIoptions\fR
]
'in \n(.iu-\nxu
.ad b
'hy
.SH DESCRIPTION
Ayatana Webmail is an application that integrates your webmail into
MATE, Xfce, LXDE and other environments. For further details see the
\fBayatana-webmail\fR(1) man page.
.PP
The \fBayatana-webmail-clear\fR executable is an internal tool of
\fBayatana-webmail\fR, does not have any command line options and should
only be used from the command line, if you know what you are doing.
.PP
\fBayatana-webmail-clear\fR is called internally by the
\fBayatana-webmail\fR app to perform the "Mark all as read" action just
as the "Clear" menu item would do in the "messages" indicator. The
message status update on the IMAP server does not happen immediately, but
only the next time the IMAP server checks in (usually within 10-20
minutes).
.PP
.SH SEE ALSO
ayatana-webmail(1), ayatana-webmail-reset(1), ayatana-webmail-settings(1), ayatana-webmail-url(1)
.SH AUTHOR
This manual has been written for the Ayatana Indicators project by Mike
Gabriel <mike.gabriel@das-netzwerkteam.de>.
