#!/bin/bash

set -e

case "$1" in

    configure)

        cp -n /usr/share/ayatanawebmail/indicator-messages-new.svg /usr/share/icons/hicolor/scalable/status/indicator-messages-new.svg
        cp -n /usr/share/ayatanawebmail/indicator-messages.svg /usr/share/icons/hicolor/scalable/status/indicator-messages.svg

        update-icon-caches /usr/share/icons/hicolor
        glib-compile-schemas /usr/share/glib-2.0/schemas
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
